### ISSUE TITLE
Messages arrives in queues but they are not sent

### ISSUE THREAD

**Issue by rdusnr** [PPFilip/smsgw-tg-amqp#1]
Hello,
I'm seeking assistance in troubleshooting a problem I'm encountering. I currently own a TG200. When I test using the default API SMS, everything works as expected. However, after installing a particular script and attempting to send a message, the message enters the queue but fails to be forwarded to TG. I suspect that the issue lies in incorrect configuration of the bindings. Could you please provide an example or a screenshot illustrating the queues and their respective bindings? I seem to have lost focus and I'm feeling stuck.

Forgot to mention,  I'm able to connect to the TG200 AMI interface via putty raw connection.

On the RabbitMQ part, any plugin it's required to be active ? i have the default installation (last version)

All the best
Radu

**Comment by PPFilip** [comment]
Hi.  Around 1 month ago the VM where this was running got drive damaged, and I did not finish the setup again, so can't screenshot my current config.  Should get fixed soon-ish though. Just to be sure ,  you want to use [amqp_consumer](https://github.com/PPFilip/smsgw-tg-amqp/tree/master/src/amqp_consumer) and forward messages from there to tg200 right?

**Comment by rdusnr** [comment]
Hello,

I appreciate your response. I've opted for a different approach and have implemented a custom queue using PHP since my application is relatively small.

Best regards,
Radu
